apiVersion: v1
kind: Pod
metadata:
  name: opencloudcx-tracer-round
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/GSA-COMET-Technical-Challenge/react-tracer-round"
    - "--destination=rivagsacomettechchal/react-tracer:latest"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: comet-dockerhub-cred
      items:
        - key: .dockerconfigjson
          path: config.json
